### PR TITLE
Refactor the CLI, improve general logic and better configuration

### PR DESCRIPTION
**Pull request by gaetschwartz**
This refactors the general structure of the cli while improving configuration and more.

### CODE REVIEW

**Comment by atreeon** [comment]
hey, apologies, I only just saw your update.  I'll take a look

**Comment by gaetschwartz** [comment]
No worries, note that some of the choices are quite opinionated as they fit my usage of the package. Feel free to tell me if there is anything you'd like to change.

**Comment by atreeon** [comment]
thanks, happy someone else has found some use out of my code!

**Comment by gaetschwartz** [comment]
Note that there is a lot more changes I'd be willing to make, but dind't want to make too big of a PR.

**Comment by atreeon** [comment]
ah great!  I had parked it for a bit but happy to pick it up a bit.  I started a small project that was using but put that on hold but I might choose that project next so I can revive this project a bit.

**Pull request closed without merging**
